version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/var/lib/postgresql/data
    network_mode: my-net

  taiga:
    build: .
    ports:
      - 80:80
      # - 443:443 # To enable SSL, uncomment this line
    restart: always
    environment:
      TAIGA_SLEEP: 20
      TAIGA_HOSTNAME: localhost
      # TAIGA_SSL: 'true' # To enable SSL, uncomment this line

      TAIGA_DB_HOST: postgres
      TAIGA_DB_NAME: taiga
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASSWORD: password
    volumes:
      - ./media:/usr/src/taiga-back/media
      - ./taiga-conf:/taiga
    network_mode: my-net
